/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package permission;

import Create.create_acc;
import Logins.login_H;
import addAccounts.add_HR;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
/**
 *
 * @author KAVI
 */
public class admin_per extends javax.swing.JFrame {

    /**
     * Creates new form admin_per
     */
    public admin_per() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnOK = new javax.swing.JButton();
        jMin1 = new javax.swing.JLabel();
        jClose1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtAdminName = new javax.swing.JTextField();
        jPasswordAdminPwd = new javax.swing.JPasswordField();
        jbtnOK1 = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();
        bakground = new javax.swing.JLabel();

        jbtnOK.setText("OK");
        jbtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOKActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMin1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMin1.setText("-");
        jMin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMin1MouseClicked(evt);
            }
        });
        getContentPane().add(jMin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 20, -1));

        jClose1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jClose1.setText("X");
        jClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jClose1MouseClicked(evt);
            }
        });
        getContentPane().add(jClose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 20, -1));

        jLabel4.setText("Login as Administrator...!");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        jLabel1.setText("Username :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        jLabel2.setText("Password :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));
        getContentPane().add(jtxtAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 100, -1));
        getContentPane().add(jPasswordAdminPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 100, -1));

        jbtnOK1.setText("OK");
        jbtnOK1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnOK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOK1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnOK1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 70, -1));

        jbtnCancel.setText("Cancel");
        jbtnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 70, -1));

        bakground.setBackground(new java.awt.Color(255, 255, 255));
        bakground.setIcon(new javax.swing.ImageIcon("D:\\PROJECTS\\HRMS\\images\\favpng_communication-consultant-management-consulting-business-cooperation.png")); // NOI18N
        getContentPane().add(bakground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 515, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMin1MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jMin1MouseClicked

    private void jClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jClose1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jClose1MouseClicked

    private void jbtnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOKActionPerformed
        
    }//GEN-LAST:event_jbtnOKActionPerformed

    private void jbtnOK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOK1ActionPerformed
        String username = jtxtAdminName.getText();
        String password = jPasswordAdminPwd.getText();

        if((username.contains("admin")) && (password.contains("1234")))
        {
            this.toBack();
            this.setVisible(false);
            new add_HR().toFront();
            new add_HR().setVisible(true);
        }
        else
        {
            jtxtAdminName.setText(null);
            jPasswordAdminPwd.setText(null);
            JOptionPane.showMessageDialog(null, "Input Wrong Username or Password", "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jbtnOK1ActionPerformed

    private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
        this.toBack();
        this.setVisible(false);
        new create_acc().toFront();
        new create_acc().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_per.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_per.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_per.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_per.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_per().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bakground;
    private javax.swing.JLabel jClose1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jMin1;
    private javax.swing.JPasswordField jPasswordAdminPwd;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnOK;
    private javax.swing.JButton jbtnOK1;
    private javax.swing.JTextField jtxtAdminName;
    // End of variables declaration//GEN-END:variables
}
