/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Logins;

import permission.admin_per;
import HRA.hra;
import HRM.hrm;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.Scanner;
import javax.swing.JFrame;
/**
 *
 * @author KAVI
 */
public class login_H extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login_H() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtUserName = new javax.swing.JTextField();
        jbtnSign = new javax.swing.JButton();
        jPassword = new javax.swing.JPasswordField();
        jbtnReset = new javax.swing.JButton();
        jClose = new javax.swing.JLabel();
        jMin = new javax.swing.JLabel();
        jbtnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User name :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 210, 140, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password   :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 260, 140, 30);
        getContentPane().add(jtxtUserName);
        jtxtUserName.setBounds(220, 210, 280, 30);

        jbtnSign.setBackground(new java.awt.Color(34, 167, 240));
        jbtnSign.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jbtnSign.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSign.setText("Sign in");
        jbtnSign.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSignActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSign);
        jbtnSign.setBounds(220, 320, 120, 40);
        getContentPane().add(jPassword);
        jPassword.setBounds(220, 260, 280, 30);

        jbtnReset.setBackground(new java.awt.Color(34, 167, 240));
        jbtnReset.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jbtnReset.setForeground(new java.awt.Color(255, 255, 255));
        jbtnReset.setText("Reset");
        jbtnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnReset);
        jbtnReset.setBounds(380, 320, 120, 40);

        jClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jClose.setForeground(new java.awt.Color(255, 255, 255));
        jClose.setText("X");
        jClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCloseMouseClicked(evt);
            }
        });
        getContentPane().add(jClose);
        jClose.setBounds(660, 20, 20, 22);

        jMin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMin.setForeground(new java.awt.Color(255, 255, 255));
        jMin.setText("-");
        jMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMinMouseClicked(evt);
            }
        });
        getContentPane().add(jMin);
        jMin.setBounds(630, 20, 20, 22);

        jbtnBack.setBackground(new java.awt.Color(255, 102, 102));
        jbtnBack.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jbtnBack.setForeground(new java.awt.Color(255, 255, 255));
        jbtnBack.setText("Login as Adminstrator");
        jbtnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBack);
        jbtnBack.setBounds(220, 370, 280, 30);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 0, 510, 460);

        background.setIcon(new javax.swing.ImageIcon("D:\\PROJECTS\\HRMS\\images\\padlock-computer-technology-wallpaper-preview.jpg")); // NOI18N
        background.setText("jLabel3");
        getContentPane().add(background);
        background.setBounds(0, 0, 700, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        
        jtxtUserName.setText(null);
        jPassword.setText(null);
        
    }//GEN-LAST:event_jbtnResetActionPerformed

    private static Scanner x ;
    
    private void jbtnSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSignActionPerformed
        
        String username= jtxtUserName.getText();
        String password= jPassword.getText();
        String filepath= "C:\\Users\\KAVI\\Desktop\\Login.txt";
        login(username,password,filepath);
    }//GEN-LAST:event_jbtnSignActionPerformed

    private void jMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jMinMouseClicked

    private void jCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jCloseMouseClicked

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        
        Object[] options= {"OK", "Cancel"};
        int response = JOptionPane.showOptionDialog(null, "Admin Use Only", "Warning",JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
        
        if (response==JOptionPane.OK_OPTION)
        {
        this.toBack();
        this.setVisible(false);
        new admin_per().toFront();
        new admin_per().setVisible(true);
        }
        else if(response==JOptionPane.CANCEL_OPTION)
                {
                
                }
        else if(response==JOptionPane.CLOSED_OPTION)
        {
        
        }
    }//GEN-LAST:event_jbtnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_H.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_H.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_H.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_H.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_H().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel jClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jMin;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnSign;
    private javax.swing.JTextField jtxtUserName;
    // End of variables declaration//GEN-END:variables
    private void systemExit()
    {
            WindowEvent WinCloseing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);    
    }
    public void close()
    {
        WindowEvent WinClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(WinClosingEvent);
        
    }
    
    public void login(String username, String password, String filepath)
    {
        boolean found = false;
        String tempUsername="";
        String tempPassword="";
        String tempDesignation="";
        
        try
        {
            FileReader fr = new FileReader(filepath);
            BufferedReader br = new BufferedReader(fr);
            x= new Scanner(br);
            x.useDelimiter("[\t\n]");
        int flag=0;
            while(x.hasNext()&& !found)
           {
               tempUsername=x.next();
               tempPassword=x.next();
               tempDesignation=x.next();
        
               username=String.valueOf(jtxtUserName.getText());
               password=String.valueOf(jPassword.getText());
               filepath=String.valueOf(br);
               
               if((tempUsername.trim().equals(username.trim())&&(tempPassword.trim().equals(password.trim()) &&
                       (tempDesignation.trim().equals("HR_Manager")))))
               {
                   this.toBack();
                   flag=0;
                   this.setVisible(false);
                   new hrm().setVisible(true);
                   break;
               }
               else if((tempUsername.trim().equals(username.trim())&&(tempPassword.trim().equals(password.trim()) &&
                       (tempDesignation.trim().equals("HR_Assistant")))))
                 {
                     this.toBack();
                     flag=0;
                     this.setVisible(false);
                     new hra().setVisible(true);
                     break;
                 }
                  else
                 {
                             System.out.println("else");
                     flag=1;
                 }
         
           }
            if(flag==1)
            {
            JOptionPane.showMessageDialog(null, "No such User Found");
            flag=0;
            }
        }
        catch(Exception e)
           {
               
           }
        
    }
}
